AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tracking-service

  Sample SAM Template for tracking-service

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  TrackingServiceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: tracking_service/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        Track:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /track
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TrackingServiceApi:
    Description: "API Gateway endpoint URL for Prod stage for Tracking Service function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/track/"
  TrackingServiceFunction:
    Description: "Tracking Service Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  TrackingServiceFunctionIamRole:
    Description: "Implicit IAM Role created for Tracking Service function"
    Value: !GetAtt TrackingServiceFunctionRole.Arn
